#!/bin/sh
set -eu

DATE="$*"

if [ -z "$DATE" ]
then
    echo -e "Usage:\n\tolder-than.sh DATE < JSON"
    echo -e "\nWhere:"
    echo -e "\tDATE - use \`date\` command syntax, e.g., 2 weeks ago"
    echo -e "\tJSON - stream of json documents generated by \`fetch-tags.sh\`, e.g., \`cat repo-image.*.json\`"
    exit 1
fi

UNIX_DATE=$(date --date="$DATE" "+%s")

jq ".tags[] | select(.start_ts < $UNIX_DATE) | .name"
